import test from 'node:test';
import assert from 'node:assert/strict';
import {detectCheckpoints,nextBoundary,evaluateAnswer,evaluateReason,addCard,rewardForCorrect,socialProofMessage,firstTryMissRate,firstTryAccuracy,checkpointGuidance} from '../src/learning.js';
import {transcript,exercises} from '../src/lesson.js';
const checkpoints=detectCheckpoints(transcript).map((c,i)=>({...c,...exercises[i]}));
test('boundaries follow completed explanations',()=>assert.deepEqual(checkpoints.map(c=>c.time),[48,96,138]));
test('forward seek pauses at first pending boundary',()=>assert.equal(nextBoundary(checkpoints,0,150,[]).time,48));
test('skip and completion prevent repeated interruption',()=>assert.equal(nextBoundary(checkpoints,0,150,['attention']).time,96));
test('backwards seek does not trigger',()=>assert.equal(nextBoundary(checkpoints,90,10,[]),undefined));
test('wrong answer provides hint',()=>assert.equal(evaluateAnswer(checkpoints[0],0,'Mọi từ như nhau'),'hint'));
test('correct without reason requests explanation',()=>assert.equal(evaluateAnswer(checkpoints[0],1,'  '),'reason'));
test('correct with reason completes',()=>assert.equal(evaluateAnswer(checkpoints[0],1,'Trọng số dựa vào ngữ cảnh'),'success'));
test('unselected answer validates',()=>assert.equal(evaluateAnswer(checkpoints[0],null,'ví dụ'),'empty'));
test('replay cannot duplicate flashcards or XP',()=>{const cards=addCard([],checkpoints[0],true);assert.equal(addCard(cards,checkpoints[0],false).length,1);assert.equal(cards[0].needsReview,true);});
test('first correct completion earns base and first-try bonus',()=>assert.equal(rewardForCorrect({alreadyCompleted:false,firstTry:true}),30));
test('correct answer after a retry earns base points only',()=>assert.equal(rewardForCorrect({alreadyCompleted:false,firstTry:false}),20));
test('replaying a completed checkpoint earns no more points',()=>assert.equal(rewardForCorrect({alreadyCompleted:true,firstTry:true}),0));
test('first-try social proof celebrates the learner against demo miss rate',()=>assert.equal(socialProofMessage({firstTry:true,missRate:90}),'Bạn đã vượt qua thử thách mà 90% người học chưa trả lời đúng ngay lần đầu!'));
test('retry social proof rewards persistence without claiming first-try success',()=>assert.equal(socialProofMessage({firstTry:false,missRate:90}),'Bạn đã sửa đúng sau khi nhận gợi ý — đó cũng là một bước tiến đáng ghi nhận.'));
test('miss rate is calculated from current participant counts',()=>assert.equal(firstTryMissRate({participants:50,firstTryCorrect:5}),90));
test('accuracy is calculated from current answer counts',()=>assert.equal(firstTryAccuracy({answered:25,firstTryCorrect:23}),92));
test('empty cohorts return zero instead of a fixed percentage',()=>assert.equal(firstTryMissRate({participants:0,firstTryCorrect:0}),0));
test('correct option with an incorrect explanation asks for revision',()=>assert.equal(evaluateAnswer(checkpoints[0],1,'Vì từ này đứng gần nhất'),'reason_feedback'));
test('teacher rubric explains which idea is missing',()=>assert.deepEqual(evaluateReason(checkpoints[0],'Vì từ này đứng gần nhất'),{status:'revise',missing:['Mức độ liên quan theo ngữ cảnh','Kết hợp thông tin theo trọng số'],feedback:'Bạn đã chọn đúng đáp án, nhưng lý do chưa cho thấy attention dựa trên mức độ liên quan trong ngữ cảnh và kết hợp thông tin theo trọng số.'}));
test('explanation matching teacher criteria passes the second review',()=>assert.deepEqual(evaluateReason(checkpoints[0],'Attention dùng trọng số để kết hợp các từ liên quan trong ngữ cảnh'),{status:'pass',missing:[],feedback:'Giải thích phù hợp với các ý chuẩn của giáo viên.'}));
test('checkpoint guidance moves learners from choosing to explaining',()=>{
  assert.deepEqual(checkpointGuidance(null,''),{answer:'current',reason:'upcoming',instruction:'Chọn một đáp án trước.'});
  assert.deepEqual(checkpointGuidance(1,''),{answer:'complete',reason:'current',instruction:'Tiếp theo, giải thích ngắn vì sao bạn chọn đáp án này.'});
  assert.deepEqual(checkpointGuidance(1,'Attention dựa vào ngữ cảnh'),{answer:'complete',reason:'complete',instruction:'Bạn đã hoàn thành 2 bước. Hãy kiểm tra lời giải.'});
});
