import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,BookmarkSimple,Cards,Check,CheckCircle,CaretDown,CaretRight,ChatCircle,Clock,FileText,Flask,Lightbulb,List,Pause,Play,Repeat,SkipForward,Sparkle,SpeakerHigh,VideoCamera,X,Lightning,ArrowCounterClockwise} from '@phosphor-icons/react';
import {transcript,exercises,duration} from './lesson';
import {detectCheckpoints,nextBoundary,addCard,timeLabel} from './learning';
import {Quiz} from './Quiz';
const checkpoints=detectCheckpoints(transcript).map((c,i)=>({...c,...exercises[i]}));
const lessons=['Giới thiệu về Generative AI','Mô hình ngôn ngữ lớn hoạt động thế nào?','Từ văn bản đến vector','Cơ chế Attention','Ứng dụng của Transformer'];
export function App(){
 const [time,setTime]=useState(35),[playing,setPlaying]=useState(false),[visited,setVisited]=useState([]),[statuses,setStatuses]=useState({}),[active,setActive]=useState(null),[cards,setCards]=useState([]),[panel,setPanel]=useState('transcript'),[flipped,setFlipped]=useState({}),[source,setSource]=useState(null),[sidebar,setSidebar]=useState(false),[auto,setAuto]=useState(true),[rate,setRate]=useState(1),[toast,setToast]=useState(''),[filter,setFilter]=useState('all');
 const current=(active?transcript.find(s=>s.start===active.start):transcript.find(s=>time>=s.start&&time<s.end))||transcript.at(-1);
 const concept=active|| (time<48?checkpoints[0]:time<96?checkpoints[1]:checkpoints[2]);
 const completed=Object.values(statuses).filter(s=>s==='done').length;
 function notify(message){setToast(message);}
 useEffect(()=>{if(!toast)return;const timeout=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timeout);},[toast]);
 function openCheckpoint(c){setTime(c.time);setPlaying(false);setActive(c);setSource(null);}
 function seek(value){const target=Number(value);const boundary=auto?nextBoundary(checkpoints,time,target,visited):null;if(boundary)openCheckpoint(boundary);else setTime(target);}
 useEffect(()=>{if(!playing||active)return;const timer=setInterval(()=>{const target=Math.min(duration,time+rate);const boundary=auto?nextBoundary(checkpoints,time,target,visited):null;if(boundary)openCheckpoint(boundary);else {setTime(target);if(target===duration)setPlaying(false);}},1000);return()=>clearInterval(timer);},[playing,time,rate,active,auto,visited]);
 function skip(){setVisited(v=>[...new Set([...v,active.id])]);setStatuses(s=>({...s,[active.id]:s[active.id]==='done'?'done':'skipped'}));setActive(null);setSource(null);setPlaying(true);notify('Điểm dừng đã bỏ qua. Bạn có thể quay lại trên timeline.');}
 function complete(c,wrong,resume){setCards(list=>addCard(list,c,wrong));setVisited(v=>[...new Set([...v,c.id])]);setStatuses(s=>({...s,[c.id]:'done'}));if(resume){setActive(null);setPlaying(true);setPanel('cards');setSource(null);}}
 function showSource(c){setSource(c);setPanel('transcript');}
 function next(){const c=checkpoints.find(c=>c.time>time&&!visited.includes(c.id))||checkpoints.find(c=>!visited.includes(c.id))||checkpoints[0];openCheckpoint(c);}
 function reset(){setTime(35);setPlaying(false);setVisited([]);setStatuses({});setCards([]);setActive(null);setSource(null);setFlipped({});notify('Đã bắt đầu lại phiên demo.');}
 return <div className="app-shell">
 <header className="topbar"><button className="icon-button mobile-menu" aria-label="Mở danh sách bài học" onClick={()=>setSidebar(!sidebar)}><List/></button><button className="icon-button back-button" aria-label="Xem danh sách bài học" onClick={()=>setSidebar(!sidebar)}><ArrowLeft/></button><span className="course-title">Bài 6 · Cơ chế Attention</span><span className="demo-label">BẢN DEMO</span><div className="header-progress"><span>{completed}/3 điểm dừng</span><progress max="3" value={completed}/></div><span className="header-xp"><Lightning weight="fill"/> {cards.length*20} XP</span><button className="header-help" onClick={()=>{setPanel('transcript');notify('Chọn một đoạn transcript để xem lại, hoặc mở checkpoint để tự kiểm tra.');}}><Sparkle/> Trợ giúp học tập</button><span className="avatar">N</span></header>
 <div className="workspace">
 <aside className={`sidebar ${sidebar?'mobile-open':''}`}><div className="module-title"><span>MODULE 1 · NỀN TẢNG AI</span><BookOpen size={18}/></div><div className="course-info"><small>AI IN ACTION 20K</small><h2>Hiểu AI, ứng dụng AI</h2><p>Học từng bước. Hiểu thật sâu.</p></div><button className="section-toggle" onClick={()=>notify('Slide bài học đang hiển thị trong khung phát.')}><span><FileText/> Slides</span><CaretRight/></button><div className="section-toggle"><span><VideoCamera/> Videos</span><CaretDown/></div><nav aria-label="Danh sách video">{lessons.map((lesson,i)=><button key={lesson} className={`lesson ${i===3?'active':''}`} onClick={()=>{if(i===3)setSidebar(false);else notify('Bản demo tập trung vào bài 6: Cơ chế Attention.');}}><span className="lesson-icon">{i<3?<CheckCircle/>:<VideoCamera/>}</span><span>{lesson}{i===3&&<small>Đang học · 3 điểm dừng</small>}</span>{i!==3&&<small>{i===4?'4':'3'} phút</small>}</button>)}</nav><div className="lab-heading"><Flask/> AI · Product Labs <CaretDown/></div>{['Sổ tay khái niệm AI','Phần 1: Khám phá bài toán','Phần 2: Thực hành cùng nhóm'].map((s,i)=><button className="lab" key={s} onClick={()=>notify('Nội dung thực hành nằm ngoài bài demo này.')}><span>{i+1}</span>{s}</button>)}<div className="sidebar-bottom"><BookOpen size={20}/><p><strong>Mỗi khái niệm, một bước tiến.</strong><small>Hiểu bài theo nhịp của riêng bạn.</small></p></div></aside>
 <main className="main"><div className="breadcrumb">Nền tảng AI <CaretRight size={13}/> Hiểu mô hình ngôn ngữ <CaretRight size={13}/> <span>Bài 6</span></div><div className="page-heading"><div><h1>Cơ chế Attention</h1><p>Hiểu cách AI tập trung vào những thông tin quan trọng.</p></div><span className="lesson-duration"><Clock/> 2 phút 30 giây</span></div>
 <div className="player-wrap"><div className="slide"><div className="slide-brand">VinUni <span>· AI in Action 20K</span></div><div className="slide-content"><span className="slide-kicker">BÀI 06 · HIỂU MÔ HÌNH NGÔN NGỮ</span><h2>{concept.id==='attention'?'Không phải từ nào cũng\nquan trọng như nhau.':concept.id==='qkv'?'Tìm đúng thông tin.\nKết hợp đúng ngữ cảnh.':'Hiểu một từ\ntrong cả ngữ cảnh.'}</h2><p className="slide-subtitle">{concept.id==='attention'?'Attention giúp mô hình biết nên “chú ý” vào đâu.':concept.id==='qkv'?'Query đặt câu hỏi · Key so khớp · Value mang thông tin.':'Self-attention kết nối các vị trí trong cùng một chuỗi.'}</p><div className="example-sentence"><small>MỘT VÍ DỤ GẦN GŨI</small><p>“Lan đưa sách cho <mark>Mai</mark> vì <mark>cô ấy</mark> cần ôn thi.”</p><span>Ngữ cảnh giúp xác định thông tin liên quan.</span></div><div className="slide-bottom"><span>ATTENTION & TRANSFORMERS</span><span>0{checkpoints.indexOf(concept)+1} / 03</span></div></div>{!playing&&!active&&<button className="play-center" aria-label="Phát video mô phỏng" onClick={()=>{if(time>=duration)setTime(0);setPlaying(true);}}><Play size={30} weight="fill"/></button>}</div>
 <div className="subtitle">{current.text}</div><div className="video-controls"><div className="timeline"><input aria-label="Tua video" type="range" min="0" max={duration} value={time} onChange={e=>seek(e.target.value)} style={{'--percent':`${time/duration*100}%`}}/>{checkpoints.map((c,i)=><button key={c.id} className={`timeline-dot ${statuses[c.id]||''}`} style={{left:`${c.time/duration*100}%`}} title={`${c.concept} · ${timeLabel(c.time)}`} aria-label={`Mở checkpoint ${i+1}: ${c.concept}`} onClick={()=>openCheckpoint(c)}>{statuses[c.id]==='done'?<Check size={10}/>:null}</button>)}</div><div className="control-row"><button aria-label={playing?'Tạm dừng':'Phát video'} className="control-icon" onClick={()=>{if(time>=duration)setTime(0);setPlaying(!playing);}}>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}</button><SpeakerHigh size={20}/><span className="timecode">{timeLabel(time)} <span>/ {timeLabel(duration)}</span></span><span className="simulated">Video mô phỏng</span><button className="speed" onClick={()=>setRate(rate===1?2:1)}>{rate}×</button><button className="control-icon" aria-label="Xem transcript" onClick={()=>setPanel('transcript')}><FileText/></button></div></div>
 {active&&<Quiz key={active.id} checkpoint={active} onSkip={skip} onComplete={complete} onSource={showSource} alreadyCompleted={statuses[active.id]==='done'}/>}</div>
 <div className="checkpoint-toolbar"><span><Sparkle weight="fill"/> Học chủ động <small>· Dừng đúng lúc, nhớ lâu hơn</small></span><label className="switch-label"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/><span className="switch"/>Tự động dừng</label></div>
 <section className="journey"><div className="section-heading"><h2>Lộ trình khái niệm <span>3 điểm dừng</span></h2><button className="text-button blue" onClick={next}>Đến checkpoint <SkipForward/></button></div><div className="checkpoint-list">{checkpoints.map((c,i)=><button key={c.id} className={`checkpoint-card ${statuses[c.id]||''} ${active?.id===c.id?'current':''}`} onClick={()=>openCheckpoint(c)}><span className="checkpoint-number">{statuses[c.id]==='done'?<Check size={18}/>:String(i+1).padStart(2,'0')}</span><span><strong>{c.concept}</strong><small>{timeLabel(c.time)} <span>·</span> {statuses[c.id]==='done'?'Đã hoàn thành':statuses[c.id]==='skipped'?'Đã bỏ qua':'Quiz + flashcard'}</small></span><CaretRight/></button>)}</div></section>
 <section className="learning-tip"><Lightbulb size={23}/><p><strong>Hiểu một khái niệm, không chỉ nhớ một đáp án.</strong><span>Thử giải thích bằng lời của bạn. Khi chưa chắc, quay lại bài giảng để tìm gợi ý.</span></p><BookmarkSimple size={22}/></section><footer className="demo-footer"><span>Transcript mẫu · Mốc khái niệm và phản hồi được mô phỏng</span><button onClick={reset}><ArrowCounterClockwise/> Làm lại demo</button></footer></main>
 <aside className="study-panel"><div className="panel-heading"><h2>Góc học tập</h2><BookOpen size={19}/></div><div className="panel-tabs" role="tablist"><button role="tab" aria-selected={panel==='transcript'} className={panel==='transcript'?'selected':''} onClick={()=>setPanel('transcript')}><FileText/> Transcript</button><button role="tab" aria-selected={panel==='cards'} className={panel==='cards'?'selected':''} onClick={()=>setPanel('cards')}><Cards/> Flashcards <span>{cards.length}</span></button></div>
 {panel==='transcript'?<><div className="panel-info"><span className="live-dot"/> Theo dòng bài giảng <span>TIẾNG VIỆT</span></div>{source&&<div className="source-preview"><div><strong>Nguồn của lời giải</strong><button className="icon-button" aria-label="Đóng nguồn" onClick={()=>setSource(null)}><X/></button></div><small>{timeLabel(source.start)}–{timeLabel(source.time)} · Transcript mẫu</small><p>“{source.source}”</p></div>}<div className="transcript-list">{transcript.map(s=><button className={`transcript-row ${current===s?'current':''}`} key={s.start} onClick={()=>{if(active)setSource({...s,source:s.text,time:s.end});else{setPlaying(false);seek(s.start);}}}><time>{timeLabel(s.start)}</time><span>{s.text}{s.boundary&&<small className="boundary-label"><Sparkle size={12}/> Kết thúc khái niệm · checkpoint</small>}</span></button>)}</div><div className="panel-bottom"><Sparkle/><span>Điểm dừng được đặt sau phần giải thích một khái niệm.</span></div></>:<div className="flashcards-panel"><div className="review-summary"><span><Cards size={24}/></span><div><strong>Bộ nhớ nhỏ, tiến bộ lớn</strong><p>{cards.length} thẻ đã thu thập · {cards.filter(c=>c.needsReview).length} cần ôn lại</p></div></div><div className="filter-tabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Tất cả</button><button className={filter==='review'?'active':''} onClick={()=>setFilter('review')}>Cần ôn lại</button></div>{cards.length===0?<div className="empty-cards"><Cards size={48}/><h3>Khái niệm được giữ lại ở đây</h3><p>Hoàn thành một checkpoint để nhận flashcard đầu tiên của bạn.</p><button className="primary" onClick={next}>Thử checkpoint <ArrowRight/></button></div>:cards.filter(c=>filter==='all'||c.needsReview).map(c=><article className="flashcard" key={c.id}><div className="flashcard-top"><span>{c.concept}</span><span>{c.needsReview?'Cần ôn lại':'Đã thu thập'}</span></div><button className="flip-area" onClick={()=>setFlipped(f=>({...f,[c.id]:!f[c.id]}))}><small>{flipped[c.id]?'LỜI GIẢI':'TỰ NHỚ LẠI'}</small><h3>{flipped[c.id]?c.answer:c.prompt}</h3><span><Repeat/> {flipped[c.id]?'Xem câu hỏi':'Chạm để lật thẻ'}</span></button>{flipped[c.id]&&<div className="review-actions"><button onClick={()=>{setCards(v=>v.map(x=>x.id===c.id?{...x,needsReview:true}:x));notify('Đã đánh dấu để ôn lại.');}}><Repeat/> Cần ôn lại</button><button onClick={()=>{setCards(v=>v.map(x=>x.id===c.id?{...x,needsReview:false}:x));notify('Đã ghi nhận tự đánh giá của bạn.');}}><Check/> Đã hiểu</button></div>}<button className="card-source" onClick={()=>showSource(c)}><FileText/> Xem nguồn · {timeLabel(c.start)}</button></article>)}{filter==='review'&&cards.length>0&&!cards.some(c=>c.needsReview)&&<p className="empty-filter">Chưa có thẻ nào cần ôn lại.</p>}<p className="review-note">XP ghi nhận việc tham gia. Hãy tự kiểm tra bằng một ví dụ mới để biết mình đã hiểu.</p></div>}</aside>
 <div className="tool-rail"><button className={panel==='transcript'?'active':''} onClick={()=>setPanel('transcript')}><FileText/><span>Transcript</span></button><button className={panel==='cards'?'active':''} onClick={()=>setPanel('cards')}><Cards/><span>Ôn tập</span></button><button onClick={()=>notify('Bạn có thể viết lý do của mình ngay trong mỗi checkpoint.')}><ChatCircle/><span>Ghi chú</span></button></div></div>{toast&&<div className="toast" role="status"><CheckCircle/>{toast}</div>}</div>;
}
