import React,{useEffect,useRef,useState} from 'react';
import {Sparkle,CheckCircle,Check,Cards,FileText,Play,Lightbulb,SkipForward,ArrowRight,Trophy} from '@phosphor-icons/react';
import {evaluateAnswer,timeLabel,rewardForCorrect,socialProofMessage} from './learning';
export function Quiz({checkpoint,onSkip,onComplete,onSource,alreadyCompleted=false}){
 const [answer,setAnswer]=useState(null),[reason,setReason]=useState(''),[feedback,setFeedback]=useState(''),[wrong,setWrong]=useState(false),[earnedPoints,setEarnedPoints]=useState(0);
 const dialog=useRef(null);
 const earnedPreviously=useRef(alreadyCompleted);
 useEffect(()=>{const previous=document.activeElement;dialog.current?.focus();return()=>previous?.focus?.();},[]);
 function submit(e){e.preventDefault();const result=evaluateAnswer(checkpoint,answer,reason);setFeedback(result);if(result==='hint')setWrong(true);if(result==='success'){setEarnedPoints(rewardForCorrect({alreadyCompleted:earnedPreviously.current,firstTry:!wrong}));onComplete(checkpoint,wrong,false);}}
 function trap(e){if(e.key==='Escape'){onSkip();return;}if(e.key!=='Tab')return;const nodes=dialog.current.querySelectorAll('button,textarea,input,[tabindex="0"]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
 return <div className="quiz-shade"><section className="quiz" role="dialog" aria-modal="true" aria-labelledby="quiz-title" tabIndex={-1} ref={dialog} onKeyDown={trap}>
  <div className="quiz-top"><span className="eyebrow"><Sparkle weight="fill"/> ĐIỂM DỪNG HỌC TẬP</span><span className="tag">{timeLabel(checkpoint.time)}</span></div>
  {feedback==='success'?<><div className="success-heading"><CheckCircle size={35} weight="fill"/><div><h2 id="quiz-title">Bạn đã chọn đúng!</h2><p>Một bước nhỏ, hiểu thêm một chút.</p></div><span className="xp-badge">{earnedPreviously.current?'Đã nhận XP':`+${earnedPoints} XP`}</span></div><div className="social-proof"><Trophy size={25} weight="fill"/><div><strong>{socialProofMessage({firstTry:!wrong,missRate:checkpoint.missRate})}</strong><small>Thống kê minh họa từ dữ liệu demo</small></div></div><p className="explanation">{checkpoint.explanation}</p><div className="reason-recap"><strong>Lý do của bạn</strong><p>{reason}</p><small>Hãy đối chiếu với lời giải mẫu; prototype chưa chấm nội dung lý do.</small></div><button className="source-link" onClick={()=>onSource(checkpoint)}><FileText/> Transcript mẫu · {timeLabel(checkpoint.start)}–{timeLabel(checkpoint.time)}</button><details className="inline-source"><summary>Đọc đoạn trích tại đây</summary><p>“{checkpoint.source}”</p></details><div className="card-added"><Cards size={23}/><span><strong>{earnedPreviously.current?'Flashcard đã có trong bộ ôn tập':'Đã thêm vào bộ ôn tập'}</strong><small>{wrong&&!earnedPreviously.current?'Flashcard này được đánh dấu cần ôn lại.':'Mở tab Flashcards để ôn lại khái niệm.'}</small></span><Check/></div><button className="primary full" onClick={()=>onComplete(checkpoint,wrong,true)}>Tiếp tục video <Play weight="fill"/></button></>:<form onSubmit={submit}>
   <div className="quiz-heading"><h2 id="quiz-title">Dừng một chút, nhớ lâu hơn.</h2><p>Bạn vừa học về <strong>{checkpoint.concept}</strong>. Thử một ví dụ mới nhé.</p></div><h3>{checkpoint.question}</h3>
   <div className="answers">{checkpoint.options.map((option,i)=><label key={option} className={`answer ${answer===i?'selected':''} ${feedback==='hint'&&answer===i?'incorrect':''}`}><input type="radio" name="answer" checked={answer===i} onChange={()=>{setAnswer(i);setFeedback('');}}/><span className="answer-letter">{'ABC'[i]}</span><span>{option}</span>{answer===i&&<Check size={18}/>}</label>)}</div>
   <label className="reason-label" htmlFor="reason">Vì sao bạn chọn đáp án này? <span>Một câu ngắn là đủ</span></label><textarea id="reason" rows={2} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Mình nghĩ rằng…"/>
   <div aria-live="polite">{feedback&&<div className={`feedback ${feedback==='hint'?'hint':''}`}><Lightbulb size={21}/><span>{feedback==='hint'?checkpoint.hint:feedback==='reason'?'Đáp án đúng rồi! Hãy thêm lý do trước khi xem lời giải.':'Bạn hãy chọn một đáp án để tiếp tục.'}</span></div>}</div>
   <div className="quiz-footer"><button type="button" className="text-button" onClick={onSkip}>Bỏ qua lúc này <SkipForward/></button><button type="submit" className="primary">{feedback==='hint'?'Thử lại':'Kiểm tra đáp án'} <ArrowRight/></button></div><p className="quiz-note">Trả lời đúng nhận 20 XP · Đúng ngay lần đầu thưởng thêm 10 XP.</p>
  </form>}
 </section></div>;
}
