export const duration=150;
export const transcript=[
 {start:0,end:12,text:'Trong bài học này, chúng ta tìm hiểu attention: cách mô hình lựa chọn thông tin liên quan trong một ngữ cảnh.'},
 {start:12,end:28,text:'Khi đọc một câu, không phải từ nào cũng đóng góp như nhau. Attention gán trọng số khác nhau cho các thành phần dựa trên mức độ liên quan.'},
 {start:28,end:42,text:'Ví dụ: “Lan đưa sách cho Mai vì cô ấy cần ôn thi.” Để hiểu “cô ấy”, mô hình cần xem xét các từ liên quan trong ngữ cảnh.'},
 {start:42,end:48,text:'Tóm lại, attention kết hợp thông tin theo trọng số phụ thuộc ngữ cảnh, thay vì coi mọi từ quan trọng như nhau.',concept:'Attention',boundary:true},
 {start:48,end:68,text:'Query biểu diễn điều đang cần tìm. Key giúp so khớp mức độ liên quan. Value là thông tin được kết hợp theo các trọng số đó.'},
 {start:68,end:84,text:'Hãy hình dung một truy vấn tìm tài liệu: query là yêu cầu, key giúp đối chiếu, còn value mang nội dung.'},
 {start:84,end:96,text:'Như vậy, Query và Key xác định trọng số liên quan; các Value được tổng hợp theo trọng số để tạo biểu diễn đầu ra.',concept:'Query · Key · Value',boundary:true},
 {start:96,end:119,text:'Self-attention áp dụng attention khi Query, Key và Value cùng được tạo từ một chuỗi đầu vào. Mỗi vị trí có thể tham chiếu các vị trí được phép trong chuỗi.'},
 {start:119,end:138,text:'Tóm lại, self-attention giúp một từ sử dụng ngữ cảnh của chính chuỗi đang xét; nó không có nghĩa là từ đó chỉ nhìn vào bản thân.',concept:'Self-attention',boundary:true},
 {start:138,end:150,text:'Bạn vừa học ba ý chính. Hãy thử giải thích bằng một ví dụ mới và ôn lại những flashcard còn chưa chắc.'}
];
export const exercises=[
 {id:'attention',concept:'Attention',responseStats:{participants:50,firstTryCorrect:5},question:'Trong câu “Nam đặt cốc lên bàn vì nó còn trống”, attention giúp mô hình làm gì khi xử lý từ “nó”?',options:['Cho mọi từ trong câu trọng số như nhau.','Cân nhắc các từ liên quan để tạo biểu diễn theo ngữ cảnh.','Luôn chọn danh từ đứng gần “nó” nhất.'],correct:1,hint:'Hãy nghĩ về mức độ liên quan trong ngữ cảnh. Khoảng cách giữa các từ không phải tiêu chí duy nhất.',explanation:'Attention tính mức độ liên quan và kết hợp thông tin theo trọng số. Cơ chế này hỗ trợ biểu diễn “nó” trong ngữ cảnh, nhưng không bảo đảm luôn giải quyết đúng mọi câu mơ hồ.',teacherDescription:'Attention đánh giá mức độ liên quan theo ngữ cảnh, sau đó kết hợp thông tin bằng các trọng số tương ứng.',teacherSources:[{id:'T06-130',excerpt:'Mỗi token nhìn các token khác, đánh giá mức tương đồng và dùng ngữ cảnh để diễn giải từ đang xét.'},{id:'T06-133',excerpt:'Self-attention xét các từ trong ngữ cảnh thay vì chỉ dựa vào vị trí gần nhất.'}],reasonRubric:[{label:'Mức độ liên quan theo ngữ cảnh',terms:['liên quan','ngữ cảnh']},{label:'Kết hợp thông tin theo trọng số',terms:['trọng số','kết hợp']}],teacherFeedback:'Bạn đã chọn đúng đáp án, nhưng lý do chưa cho thấy attention dựa trên mức độ liên quan trong ngữ cảnh và kết hợp thông tin theo trọng số.',prompt:'Attention khác việc coi mọi từ quan trọng như nhau như thế nào?',answer:'Attention gán trọng số theo mức độ liên quan trong ngữ cảnh, rồi kết hợp thông tin theo các trọng số đó.'},
 {id:'qkv',concept:'Query · Key · Value',responseStats:{participants:50,firstTryCorrect:18},question:'Khi tìm thông tin như tra cứu một tài liệu, thành phần nào mang nội dung được tổng hợp để tạo đầu ra?',options:['Query — điều đang cần tìm.','Key — thông tin dùng để so khớp.','Value — thông tin được kết hợp.'],correct:2,hint:'Query và Key giúp tính độ liên quan. Thành phần còn lại mang nội dung cần kết hợp.',explanation:'Query được so khớp với các Key để tính trọng số. Đầu ra là tổ hợp các Value theo những trọng số đó.',teacherDescription:'Query và Key được so khớp để tạo trọng số; Value mang nội dung được tổng hợp thành đầu ra.',teacherSources:[{id:'T06-130',excerpt:'Query là truy vấn, Key là nhãn và Value là nội dung.'},{id:'T06-131',excerpt:'Query được so với Key; Value là nội dung gắn với Key.'}],reasonRubric:[{label:'Query và Key dùng để so khớp',terms:['so khớp','query','key']},{label:'Value mang nội dung được kết hợp',terms:['value','nội dung','kết hợp']}],teacherFeedback:'Bạn đã chọn đúng Value, nhưng cần nói rõ Query và Key dùng để so khớp, còn Value mang nội dung được kết hợp theo trọng số.',prompt:'Query, Key và Value đảm nhiệm vai trò nào?',answer:'Query: điều cần tìm. Key: thông tin để so khớp. Value: nội dung được tổng hợp theo trọng số liên quan.'},
 {id:'self',concept:'Self-attention',responseStats:{participants:50,firstTryCorrect:14},question:'“Self” trong self-attention có nghĩa là gì?',options:['Mỗi từ chỉ được nhìn vào chính nó.','Query, Key và Value được tạo từ cùng một chuỗi đầu vào.','Mô hình không cần thông tin ngữ cảnh.'],correct:1,hint:'“Self” nói về nguồn của Query, Key và Value, không phải việc một từ bị cô lập.',explanation:'Trong self-attention, Query, Key và Value cùng xuất phát từ một chuỗi. Mỗi vị trí vẫn có thể sử dụng thông tin từ các vị trí khác được phép bởi attention mask.',teacherDescription:'Query, Key và Value được tạo từ cùng một chuỗi; mỗi vị trí vẫn có thể dùng ngữ cảnh từ các vị trí được phép.',teacherSources:[{id:'T06-086',excerpt:'Mỗi token nhìn các token khác trong ngữ cảnh.'},{id:'T06-126',excerpt:'Self-attention cho phép các token nhìn nhau và xử lý song song.'}],reasonRubric:[{label:'Cùng một chuỗi đầu vào',terms:['cùng một chuỗi','chuỗi đầu vào']},{label:'Vẫn sử dụng ngữ cảnh giữa các vị trí',terms:['ngữ cảnh','vị trí','tham chiếu']}],teacherFeedback:'Bạn đã chọn đúng, nhưng “self” không có nghĩa là mỗi từ chỉ nhìn chính nó. Query, Key và Value cùng đến từ một chuỗi và các vị trí vẫn dùng ngữ cảnh của nhau.',prompt:'Self-attention có phải mỗi từ chỉ nhìn chính nó?',answer:'Không. Nó tham chiếu các vị trí được phép trong cùng chuỗi; Query, Key và Value đều được tạo từ chuỗi đó.'}
];
