import React,{useEffect,useRef,useState} from 'react';
import {Sparkle,CheckCircle,Check,Cards,FileText,Play,Lightbulb,SkipForward,ArrowRight,Trophy} from '@phosphor-icons/react';
import {timeLabel,rewardForCorrect,socialProofMessage,firstTryMissRate} from './learning';
import {reviewExplanation} from './reviewApi';

const verdictHeading={misconception:'Cách hiểu này còn một điểm chưa đúng',insufficient:'Phần giải thích chưa đủ căn cứ',out_of_scope:'Nội dung này nằm ngoài checkpoint'};

export function Quiz({checkpoint,onSkip,onComplete,onSource,alreadyCompleted=false}){
 const [answer,setAnswer]=useState(null),[reason,setReason]=useState(''),[feedback,setFeedback]=useState(''),[wrong,setWrong]=useState(false),[earnedPoints,setEarnedPoints]=useState(0),[aiReview,setAiReview]=useState(null),[reviewError,setReviewError]=useState('');
 const dialog=useRef(null);
 const earnedPreviously=useRef(alreadyCompleted);
 const reviewing=feedback==='reviewing';
 useEffect(()=>{const previous=document.activeElement;dialog.current?.focus();return()=>previous?.focus?.();},[]);
 async function submit(e){e.preventDefault();if(answer===null){setFeedback('empty');return;}if(answer!==checkpoint.correct){setWrong(true);setFeedback('hint');return;}if(!reason.trim()){setFeedback('reason');return;}setFeedback('reviewing');setAiReview(null);setReviewError('');try{const review=await reviewExplanation({checkpointId:checkpoint.id,answer,explanation:reason});setAiReview(review);if(review.passed){setFeedback('success');setEarnedPoints(rewardForCorrect({alreadyCompleted:earnedPreviously.current,firstTry:!wrong}));onComplete(checkpoint,wrong,false);}else{setWrong(true);setFeedback('ai_feedback');}}catch(error){setReviewError(error.message);setFeedback('ai_error');}}
 function chooseAnswer(index){setAnswer(index);setFeedback('');setAiReview(null);setReviewError('');}
 function updateReason(value){setReason(value);if(feedback==='ai_feedback'||feedback==='ai_error'){setFeedback('');setAiReview(null);setReviewError('');}}
 function trap(e){if(e.key==='Escape'){onSkip();return;}if(e.key!=='Tab')return;const nodes=dialog.current.querySelectorAll('button,textarea,input,[tabindex="0"]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
 return <div className="quiz-shade"><section className="quiz" role="dialog" aria-modal="true" aria-labelledby="quiz-title" tabIndex={-1} ref={dialog} onKeyDown={trap}>
  <div className="quiz-top"><span className="eyebrow"><Sparkle weight="fill"/> ĐIỂM DỪNG HỌC TẬP</span><span className="tag">{timeLabel(checkpoint.time)}</span></div>
  {feedback==='success'?<><div className="success-heading"><CheckCircle size={35} weight="fill"/><div><h2 id="quiz-title">Bạn đã chọn đúng!</h2><p>Đáp án và phần giải thích đã được OpenAI đối chiếu với ý chuẩn của giáo viên.</p></div><span className="xp-badge">{earnedPreviously.current?'Đã nhận XP':`+${earnedPoints} XP`}</span></div><div className="social-proof"><Trophy size={25} weight="fill"/><div><strong>{socialProofMessage({firstTry:!wrong,missRate:firstTryMissRate(checkpoint.responseStats)})}</strong><small>Tính từ {checkpoint.responseStats.participants} lượt tham gia mẫu · sẽ dùng dữ liệu thật khi tích hợp</small></div></div><p className="explanation">{checkpoint.explanation}</p><div className="reason-recap"><strong>Lý do của bạn</strong><p>{reason}</p><small>AI verdict: correct · Nguồn {aiReview?.source_ids.join(', ')||'giáo viên'}</small></div><button className="source-link" onClick={()=>onSource(checkpoint)}><FileText/> Transcript mẫu · {timeLabel(checkpoint.start)}–{timeLabel(checkpoint.time)}</button><details className="inline-source"><summary>Đọc đoạn trích tại đây</summary><p>“{checkpoint.source}”</p></details><div className="card-added"><Cards size={23}/><span><strong>{earnedPreviously.current?'Flashcard đã có trong bộ ôn tập':'Đã thêm vào bộ ôn tập'}</strong><small>{wrong&&!earnedPreviously.current?'Flashcard này được đánh dấu cần ôn lại.':'Mở tab Flashcards để ôn lại khái niệm.'}</small></span><Check/></div><button className="primary full" onClick={()=>onComplete(checkpoint,wrong,true)}>Tiếp tục video <Play weight="fill"/></button></>:<form onSubmit={submit}>
   <div className="quiz-heading"><h2 id="quiz-title">Dừng một chút, nhớ lâu hơn.</h2><p>Bạn vừa học về <strong>{checkpoint.concept}</strong>. Thử một ví dụ mới nhé.</p></div><h3>{checkpoint.question}</h3>
   <div className="answers">{checkpoint.options.map((option,i)=><label key={option} className={`answer ${answer===i?'selected':''} ${feedback==='hint'&&answer===i?'incorrect':''}`}><input type="radio" name="answer" checked={answer===i} disabled={reviewing} onChange={()=>chooseAnswer(i)}/><span className="answer-letter">{'ABC'[i]}</span><span>{option}</span>{answer===i&&<Check size={18}/>}</label>)}</div>
   <label className="reason-label" htmlFor="reason">Vì sao bạn chọn đáp án này? <span>Một câu ngắn là đủ</span></label><textarea id="reason" rows={2} value={reason} disabled={reviewing} maxLength={1200} onChange={e=>updateReason(e.target.value)} placeholder="Mình nghĩ rằng…"/>
   <div aria-live="polite">{feedback==='reviewing'&&<div className="ai-reviewing"><Sparkle/><span><strong>OpenAI đang đối chiếu lời giải…</strong>Kiểm tra theo câu hỏi mẫu, rubric và transcript giáo viên.</span></div>}{feedback==='ai_feedback'&&aiReview&&<div className="teacher-feedback ai-feedback"><div><Lightbulb size={22}/><span><strong>{verdictHeading[aiReview.verdict]||'Cần xem lại lời giải'}</strong>{aiReview.feedback}</span></div>{aiReview.misconceptions.length>0&&<><small>ĐIỂM HIỂU SAI</small><div className="missing-criteria">{aiReview.misconceptions.map(item=><span key={item}>{item}</span>)}</div></>}{aiReview.missing_ideas.length>0&&<><small>Ý CẦN BỔ SUNG</small><div className="missing-criteria">{aiReview.missing_ideas.map(item=><span key={item}>{item}</span>)}</div></>}<p className="next-question"><strong>Thử nghĩ tiếp:</strong> {aiReview.next_question}</p><div className="ai-source"><FileText/> Nguồn giáo viên: {aiReview.source_ids.join(', ')||'rubric checkpoint'}</div></div>}{feedback==='ai_error'&&<div className="ai-error"><Lightbulb/><span><strong>Chưa thể xác minh bằng AI</strong>{reviewError}</span></div>}{feedback&&['hint','reason','empty'].includes(feedback)&&<div className={`feedback ${feedback==='hint'?'hint':''}`}><Lightbulb size={21}/><span>{feedback==='hint'?checkpoint.hint:feedback==='reason'?'Đáp án đúng rồi! Hãy thêm lý do trước khi gửi OpenAI kiểm tra.':'Bạn hãy chọn một đáp án để tiếp tục.'}</span></div>}</div>
   <div className="quiz-footer"><button type="button" className="text-button" disabled={reviewing} onClick={onSkip}>Bỏ qua lúc này <SkipForward/></button><button type="submit" className="primary" disabled={reviewing}>{reviewing?'Đang kiểm tra…':feedback==='hint'?'Thử lại':feedback==='ai_feedback'||feedback==='ai_error'?'Kiểm tra lại giải thích':'Kiểm tra bằng AI'} {!reviewing&&<ArrowRight/>}</button></div><p className="quiz-note">Đáp án và giải thích đều đúng: +20 XP · Qua ngay lần đầu: thưởng thêm 10 XP.</p>
  </form>}
 </section></div>;
}
